# Generated by Django 3.2.12 on 2022-04-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(default='3930-1719-7522-1032', max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ifse_code', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_initiated_type', models.CharField(choices=[('Manual', 'Manual'), ('DialogFlow', 'DialogFlow')], max_length=20)),
                ('receiver_name', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Acted upon', 'Acted upon'), ('pending', 'pending'), ('Failed', 'Failed')], default='pending', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('Insufficient Fund', 'Insufficient Fund'), ('pending', 'pending')], default='pending', max_length=40)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.bankaccount', to_field='account_number')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('is_active', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], max_length=15)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.bankaccount', to_field='account_number')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.bankbranch', to_field='name')),
            ],
        ),
    ]
