# Generated by Django 3.2.12 on 2022-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='1235-7772-5930-7806', max_length=19, unique=True),
        ),
    ]
