# Generated by Django 3.2.12 on 2022-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20220415_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='1322-5749-6834-9831', max_length=19, unique=True),
        ),
    ]
