# Generated by Django 3.2.12 on 2022-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='1896-0330-2149-5734', max_length=19, unique=True),
        ),
    ]
