# Generated by Django 3.2.12 on 2022-04-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20220416_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='1628-1690-5283-5196', max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='transaction.customer'),
        ),
    ]
